In [1]:
# autograd


In [2]:
import torch
x = torch.rand(3, requires_grad=True)
print(x)

tensor([0.4299, 0.9723, 0.3200], requires_grad=True)


In [3]:
y = x+3

In [4]:
print(y)

tensor([3.4299, 3.9723, 3.3200], grad_fn=<AddBackward0>)


In [5]:
z = y*y*2
z = z.mean() # produce the mean values of the z vector.
print(z)


tensor(25.7105, grad_fn=<MeanBackward0>)


In [11]:
#z.backward()
print(x.grad) # where the gradients has been stored. A jacobian matrix is formed and it is multiplied with
              # the gradient matrix formed. 



tensor([4.5732, 5.2964, 4.4267])
None


/tmp/ipykernel_46713/539906059.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(z.grad)


In [17]:
weight = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output =(weight*3).sum()
    model_output.backward()
    print(weight.grad)
    weight.grad.zero_() # erases the gradient values stored in weight.

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
